### ISSUE TITLE
[Bug] Forge Doesn’t Install

### ISSUE THREAD

**Issue by SailentWasTaken** [PojavLauncherTeam/PojavLauncher_iOS#258] opened 2021-08-17 19:15 UTC
### Describe the bug

I’ve already installed Forge 1.16.5 but when I try to install it for 1.8.9 (I have JDK-8-jre installed) it shows this message. I’ve also done CD, I’ve done the file names correctly (I just changed it)

### The log file and images/videos

![2DCB99F1-8609-44A7-9425-68AC582E806A](https://user-images.githubusercontent.com/71612086/129786707-4c1eedc7-10ea-4b69-83c0-3cef98e2e196.png)

### Steps To Reproduce

```markdown
1. Download the Forge 1.8.9 Jar & The Headless Installer.
2. Try to install it normally from the tutorial given in “Installing Non - Vanilla Versions Of Minecraft)
```

### Expected Behavior

It installs forge for 1.8.9

### Platform

```markdown
- Device model: iPad 6th Generation
- iOS version: 14.3
- PojavLauncher version: 1.3
```

**Comment by khanhduytran0** [comment] 2021-08-19 01:12
Likely duplicate of #257. Why would you have to split issues on attempt of installing a same thing?


Forge headless installer only supports Minecraft 1.13+.

**Closed by khanhduytran0** 2021-08-19 01:12 UTC
Labels: bug
