### ISSUE TITLE
[F-Req] Add This?

### ISSUE THREAD

**Issue by SailentWasTaken** [PojavLauncherTeam/PojavLauncher_iOS#255] opened 2021-08-16 13:47 UTC
### Is this request related to a bug?

I’ve heard that keyboard support is added and I would like to ask for controller support because as a MCPE / Bedrock player I’ve been using controller on the game for a few months and would really appreciate if you could try & add gameplay support for controller (DualShock 4 or XBOX But I request you add DualShock 4 first if you do add support)
I hope this is possible. - SailentTech

**Comment by khanhduytran0** [comment] 2021-08-19 01:06
**Minecraft Java doesn't support controller**. The only way to play with a controller is to use a mod or we have to map it manually (but I don't have any controllers to map).

**Comment by khanhduytran0** [comment] 2021-08-19 01:19
Duplicate of #74

**Closed by khanhduytran0** 2021-08-19 01:19 UTC
Labels: enhancement
