### ISSUE TITLE
Can't scroll on the hotbar with external mouse

### ISSUE THREAD

**Issue by Figurant16** [PojavLauncherTeam/PojavLauncher_iOS#396] opened 2022-10-11 12:39 UTC
### Describe the bug

When I plug an external mouse, i can't scroll in my hotbar.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
```

### Expected Behavior

The hotbar scroll.

### Platform

```markdown
- Device model: iPad Pro 2021
- iOS version: iPadOS 16.1 Beta
- PojavLauncher version: 2.1
```

### Anything else?

Maybe that's caused by the iPadOS beta ?

**Comment by khanhduytran0** [comment] 2022-10-11 23:37
Duplicate of #390
Also, there isn’t enough info, no tested Minecraft version, does regular scrolling work, etc..?

**Closed by khanhduytran0** 2022-10-11 23:37 UTC
Labels: bug

**Comment by InfernoNova9999** [comment] 2022-10-12 03:49
I fixed this issue by installing debugify mod. If that doesnt work, go the settings, general, keyboard, hardware keybords, function keys and make sure you didnt map the caps lock key to something else
