### ISSUE TITLE
[Bug] Minecraft 1.17+ not working

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#321] opened 2022-02-10 11:14 UTC
### Describe the bug

Crashing at startup

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/8040455/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login as Demo User
3. Open menu options
4. Setting to java 16
5. Setting renderer to tinygl4angle
6. Restart PojavLauncher
7. Start PojavLauncher again
8. Login as Demo User again
9. Select 1.17 mc version
10. Click play
11. Crash
```

### Expected Behavior

I expect the game to start normally

### Platform

```markdown
- Device model: iPhone 7 (GSM)
- iOS version: 14.3
- PojavLauncher version: latest dev build from Github actions
```

### Anything else?

/

**Comment by AyanKadri** [comment] 2022-02-11 13:33
1.18 not working

**Comment by Doregon** [comment] 2022-03-04 12:44
Closing this issue and #312 for multiple reasons

1. You lied about using the demo user and are in fact using local mode, which we stated will not be supported.

2. We are hnable to reproduce this issue with the latest development builds and proper settings.

**Closed by Doregon** 2022-03-04 12:44 UTC
Labels: bug

**Comment by admin-elvistrujanovic** [comment] 2022-03-06 20:54
> Closing this issue and #312 for multiple reasons
> 
> 1. You lied about using the demo user and are in fact using local mode, which we stated will not be supported.
> 
> 2. We are hnable to reproduce this issue with the latest development builds and proper settings.

1. If you think so that I'm lied about using the demo user I can send you my demo user json file to see contents in it that is valid and you can test it yourself to login and play with my account json file

2. Due to a lot of instability and errors during the return to the older version via FutureRestore, due to which I can not run regular Minecraft for iOS (ipa), I come to the conclusion that this is a bug from the iOS system itself. I even have a cr4shed report file for Minecraft.ipa which clearly indicates that some components from the iOS system just don't work. I can't even open the banking application after the restore process. I do not recommend anyone to perform the restore process on iPhone 7 GSM from 14.5 version to any version that is lower than 14.4+

3. It's not nice to judge immediately after the first ball the way it comes to a person you don't even know in real life.
- Please be careful what you write and how you express yourself not to insult anyone.
If you have something to say like this, do it via DM with an apology

Thanks in advance and thanks for reading all this

Have a good day!

**Comment by Doregon** [comment] 2022-03-06 22:09
> > Closing this issue and #312 for multiple reasons
> > 
> > 1. You lied about using the demo user and are in fact using local mode, which we stated will not be supported.
> > 2. We are hnable to reproduce this issue with the latest development builds and proper settings.
> 
> 1. If you think so that I'm lied about using the demo user I can send you my demo user json file to see contents in it that is valid and you can test it yourself (to login and play with my account json file)
> 2. Due to a lot of instability and errors during the return to the older version via FutureRestore, due to which I can not run regular Minecraft for iOS (ipa), I come to the conclusion that this is a bug from the iOS system itself. I even have a cr4shed report file for Minecraft.ipa which clearly indicates that some components from the iOS system just don't work. I can't even open the banking application after the restore process. I do not recommend anyone to perform the restore process on iPhone 7 GSM from 14.5 version to any version that is lower than 14.4+
> 3. It's not nice to judge immediately after the first ball the way it comes to a person you don't even know in real life.
> 
> * Please be careful what you write and how you express yourself not to insult anyone.
>   If you have something to say like this, do it via DM with an apology
> 
> Thanks in advance and thanks for reading all this
> 
> Have a good day!

1. In PojavLauncher code, the demo user only works if the name is set to `demo_user`. In your logs, the name is not `demo_user`, meaning that you are not using the demo account, and failed to authenticate meaning that you are not logged in with a valid token. This boils down to the simple fact that you are requesting help for a local mode issue which we will not support, period.

2. If that is the case, then we still cannot help you as we do not have these same issues as you and cannot reproduce this problem.

3. I'm not judging you immediately based on this issue. I'm using existing experience I've had with you in our Discord server where you said that you would rather save up for an Android phone and continue to pirate the game.

**Comment by admin-elvistrujanovic** [comment] 2022-03-07 08:48
> > > Closing this issue and #312 for multiple reasons
> 
> > > 
> 
> > > 1. You lied about using the demo user and are in fact using local mode, which we stated will not be supported.
> 
> > > 2. We are hnable to reproduce this issue with the latest development builds and proper settings.
> 
> > 
> 
> > 1. If you think so that I'm lied about using the demo user I can send you my demo user json file to see contents in it that is valid and you can test it yourself (to login and play with my account json file)
> 
> > 2. Due to a lot of instability and errors during the return to the older version via FutureRestore, due to which I can not run regular Minecraft for iOS (ipa), I come to the conclusion that this is a bug from the iOS system itself. I even have a cr4shed report file for Minecraft.ipa which clearly indicates that some components from the iOS system just don't work. I can't even open the banking application after the restore process. I do not recommend anyone to perform the restore process on iPhone 7 GSM from 14.5 version to any version that is lower than 14.4+
> 
> > 3. It's not nice to judge immediately after the first ball the way it comes to a person you don't even know in real life.
> 
> > 
> 
> > * Please be careful what you write and how you express yourself not to insult anyone.
> 
> >   If you have something to say like this, do it via DM with an apology
> 
> > 
> 
> > Thanks in advance and thanks for reading all this
> 
> > 
> 
> > Have a good day!
> 
> 
> 
> 1. In PojavLauncher code, the demo user only works if the name is set to `demo_user`. In your logs, the name is not `demo_user`, meaning that you are not using the demo account, and failed to authenticate meaning that you are not logged in with a valid token. This boils down to the simple fact that you are requesting help for a local mode issue which we will not support, period.
> 
> 
> 
> 2. If that is the case, then we still cannot help you as we do not have these same issues as you and cannot reproduce this problem.
> 
> 
> 
> 3. I'm not judging you immediately based on this issue. I'm using existing experience I've had with you in our Discord server where you said that you would rather save up for an Android phone and continue to pirate the game. 

1. I edited manually my demo user json file to allow full access to downloaded game (edited username and access token) but I didn't remove other informations from the file like profile ID

2. Yes - it's true

3. Yes - I will pirate the game but not in the PojavLauncher, I will use MCinaBox or any alternatives that is available on Android - not on iOS

**Comment by CriticalRange** [comment] 2022-03-07 11:11
> 

Good luck using LaginaBox, :frpirate:

**Comment by admin-elvistrujanovic** [comment] 2022-03-07 12:31
@artdeell @CriticalRange and @everyone-else I will ask everyone here not to comment on this issue except @Doregon because this issue is now closed and it will be closed forever - this is a conversation exclusively between me and Doregon.

**Comment by artdeell** [comment] 2022-03-07 14:24
All GitHub issues, even after closing, remain public domain and accessible for everyone, until they are locked or deleted. If you want an exclusive conversation - please use Telegram or Discord or whatever

**Comment by Doregon** [comment] 2022-03-07 23:29
> 1. I edited manually my demo user json file to allow **full access to downloaded game** (edited username and access token) but I didn't remove other informations from the file like profile ID. If you want, I can run again the game with the same problem without editing account json file manually so the account json file will not be pirated
> 2. Yes - it's true
> 3. Yes - I will pirate the game but not in the PojavLauncher, I will use MCinaBox or any alternatives that is available on Android - not on iOS

1. So you just confirmed that you in fact converted the demo user json file into an offline mode json file.
2. No response.
3. Then we will no longer provide support for issues made by a known pirate, as we do not wish to be associated with this (especially since Microsoft has sent me a DMCA notice about offline mode already).

Locking this issue as nothing productive is coming out of it.
