### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by ExeRhythm** [PojavLauncherTeam/PojavLauncher_iOS#128] opened 2021-04-08 17:27 UTC
**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.

iPadOS 14.3 latest PojavLauncher build
**Next, describe the issue.**
Make sure to be as descriptive as possible. 

Cannot log into my Microsoft account

**What’s supposed to happen?**
What were you expecting?

I should've been redirected to the game with my account I just logged into.

**How does it happen?**
Let’s get a step by step on how to reproduce this issue.

Log into Microsoft account

**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

![image](https://user-images.githubusercontent.com/52459150/114070482-b8f62980-98a8-11eb-808f-efe8221f4a64.jpeg)

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by Doregon** [comment] 2021-04-15 03:49
Dupe of #126

**Comment by ExeRhythm** [comment] 2021-04-17 17:02
The issue still persists in the latest build

**Closed** 2021-04-24 04:43 UTC
Labels: bug
