### ISSUE TITLE
[Bug] PojavLauncher IOS Crashes when opening a existing world

### ISSUE THREAD

**Issue by BostoTheGhost** [PojavLauncherTeam/PojavLauncher_iOS#453] opened 2022-12-16 05:58 UTC
### Describe the bug

I just got Pojavlancher a few days ago (Making this in 12/15/2022) This was around the time that 2.1 version of Pojavlancher came out. Well the game runs really well but the only problem is that when I make a new world, leave it then go and join it again to continue the game it gets stuck on the loading screen. The one with the black box as the map loads in won't load. It stays at 0% and then crashes. I got the game on AltStore and my IOS device is not jailbroken.

I have no idea what to do and I'm getting really confused. I've searched up ways to fix it but to no avail it was no use. Nobody has seemed to have the same problems as me and I have no idea how to fix it.

Please get back to me as soon as possible I really want to play a hardcore world on my phone. Thank you

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start up already exisiting world
3. game freezes at the world loading
4. PojavLauncher crashes
```

### Expected Behavior

I generally just expect the game to open up my world and I can continue my world but it crashes instead

### Platform

```markdown
- Device model: Iphone 12,8
- iOS version: 16.1
- PojavLauncher version: 2.1
```

**Comment by Tatouu14** [comment] 2022-12-16 07:57
Exactly the same thing has happened to me, a "solution", is to add a little more ram to the game or use fabric optimization mods so that the game is more fluid without assigning more ram, (assigning more ram brings problems with the game closing in short periods while you travel the world.)

**Comment by khanhduytran0** [comment] 2022-12-18 05:01
Check if Analytics Data has PojavLauncher.ips and if so, please send it

**Comment by JuJuDinkyDoo** [comment] 2023-01-03 04:31
This is happening on android for me too :(

**Comment by abhishekgi** [comment] 2023-02-08 16:16
This is happening to me also 
Pojav launcher crashes anytime on my iPad 9  using altstore 
Ipad-16
Pojav launcher crashes on open preloaded world's 
Sometimes it crashes While changing settings it crashes when i am running in game and the worst thing if you are on altstore and you have to install optifine then you will click on 
Install jar and click on install after optifine has been installed there is no way to come back to main menu the only option is close pojav launcher and enable jit again

**Comment by crystall1nedev** [comment] 2023-04-20 14:17
can't reproduce this on the latest builds, plus stale issue. closing

**Closed by crystall1nedev** 2023-04-20 14:17 UTC
Labels: bug
