### ISSUE TITLE
[zink] Why can't m2 use zink renderer?

### ISSUE THREAD

**Issue by XEYt44** [PojavLauncherTeam/PojavLauncher_iOS#470] opened 2023-01-02 18:16 UTC
### Describe the bug

m2I can't use the zink renderer. I've been asked a lot.，m2bemetal 3butzinkbemetal 2The problem?
Will it be repaired in the future?

### The log file and images/videos

![6DBEF509-466C-4BA7-8485-BB92ABF6EBDD](https://user-images.githubusercontent.com/121798130/210266583-4f35ce39-9113-4f8f-8eab-1c1de009242d.jpeg)
![5BAF580D-11C7-41A8-A221-CF07CEC1685D](https://user-images.githubusercontent.com/121798130/210266587-e48dd44b-ff8a-4ce6-89e2-041e88e4aaad.jpeg)

### Steps To Reproduce

```markdown
Zink renderer repeats black screen
```

### Expected Behavior

I hope the renderer can be compatible with m2 processor.

### Platform

```markdown
- Device model: ipad pro 2022
- iOS version: 16.1.1
- PojavLauncher version: 2.1.2
```

**Comment by Bitboss2** [comment] 2023-01-02 19:48
You are not only you, I have the same bug and I have an iPad Air 4 with iOS 16. I tried on an iPad 8th gen with iOS 15 and it works with seus Ptgi Hrr 2.1. I think the problem is the new metal api on iOS 16.

**Comment by XEYt44** [comment] 2023-01-02 20:03
![C4B02272-6CF6-40A5-95BA-F1B62675CB29](https://user-images.githubusercontent.com/121798130/210274132-c765be02-cb00-4a71-a92a-d5a32407d903.jpeg)
![E4813DD3-967B-4756-8DDA-F526B08D463C](https://user-images.githubusercontent.com/121798130/210274144-098b53af-063f-46c8-b72d-84a8c47b9b9d.png)

**Comment by XEYt44** [comment] 2023-01-02 20:07
> My iphonexr is very smooth, and both high and low versions of zink renderer can use Troll 15.4.1.

**Comment by imUrban** [comment] 2023-01-07 01:01
the problem might be the java runtime environment detected fatal errors

**Comment by khanhduytran0** [comment] 2023-01-20 14:46
Duplicate of #469

**Closed by khanhduytran0** 2023-01-20 14:46 UTC
Labels: bug
