### ISSUE TITLE
[Bug] <Short description>

### ISSUE THREAD

**Issue by Blockbuster-MC** [PojavLauncherTeam/PojavLauncher_iOS#405] opened 2022-10-15 02:22 UTC
### Describe the bug

iOS Controller Mapping - Bumpers - Hotbar

As i have been using controller more and more i have come to realize that there is no way to switch between items in your inventory.

Would it be possible for you to map left bumper to scroll wheel up once and right bumper to scroll wheel down once?

@khanhduytran0 

### Steps To Reproduce

```markdown
Use a controller on PoJav
```

### Expected Behavior

inventory to switch, instead left and right bumper also do the same thing left and right trigger do.

### Platform

```markdown
- Device model: iphone 12 pro max
- iOS version: 
- PojavLauncher version: 385
```

**Comment by khanhduytran0** [comment] 2022-10-15 02:40
Duplicate of #397
This is a known issue. As I don’t have controller to test, I don’t know what’s going on, as what I know so far is the programmed code.
If you want to report testings, please join our discord server.

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/blob/1a1b829698c8b57f018e07eae1bf551909d89467/Natives/input/ControllerInput.m#L31-L32

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/blob/1a1b829698c8b57f018e07eae1bf551909d89467/Natives/input/ControllerInput.m#L117-L122

**Closed by khanhduytran0** 2022-10-15 02:40 UTC
Labels: bug

**Comment by Blockbuster-MC** [comment] 2022-10-15 11:22
hmmm, could you try using dpad left an dpad right to those mappings and see if that worked.  I can also just send you a controller.

**Comment by Blockbuster-MC** [comment] 2022-10-15 12:29
> Mapping issue should have already been fixed, try the latest build.

from what i can tell, the d-pad mappings are

Left DPAD = J
Down DPAD = 0 or O
Right DPAF = K

And i am unaware on how to switch those mappings

As for the discord, I am on it, however, because I can't verify my account I can't post in certain channels.  My Minecraft account got migrated to my professional email and i prefer not to link that to video game related things for obvious reasons.
