### ISSUE TITLE
App Crashing bug...

### ISSUE THREAD

**Issue by WillXProject** [PojavLauncherTeam/PojavLauncher_iOS#121] opened 2021-04-04 23:04 UTC
I am using iPadOS 14.2 Unc0ver 6.0.1 Pojavlauncher - Latest

I open the app and my screen becomes black, then crashes the app.

First startup screen

Open the app

I can send a video https://youtu.be/9ibLWg9GTvA

**Please verify that you have done the following:**

- [x] Provided details on what you’re seeing vs what you wanted
- [x] Provided a log file, if relevant
- [x] Provided steps to reproduce this issue
- [x] Tested on the latest version of PojavLauncher

**Comment by WillXProject** [comment] 2021-04-04 23:15
[text.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6255607/text.txt)
found the log!

**Comment by Doregon** [comment] 2021-04-06 05:08
Duplicate of #119

**Closed** 2021-04-06 08:15 UTC
Labels: bug, duplicate
