### ISSUE TITLE
Why sink render doesn’t work on iOS 16

### ISSUE THREAD

**Issue by Zkiai** [PojavLauncherTeam/PojavLauncher_iOS#475] opened 2023-01-04 14:13 UTC
### Describe the bug

Hello I have a bug when I updated my phone on iOS 16. The zink render doesn’t work. I just have a black screen and sound. What can I do to solve this problem, before I played with shaders ( complemtary shaders ) and had 40/45 fps. 

### The log file and images/videos

![BE00D659-FB93-4D3C-8434-53AFB9B06B2B](https://user-images.githubusercontent.com/121922866/210572561-15398f6b-fe5d-46ae-9c0e-db8f75a4bbf8.png)
[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10344759/latestlog.old.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Choose on settings sink render 
3. Choose any Minecraft version
4. Tap on play button
```

### Expected Behavior

X

### Platform

```markdown
- Device model:iPhone 12
- iOS version:16.2
- PojavLauncher version:2.1.2
```

### Anything else?

Plz solve this problem I would like to run shaders

**Comment by imUrban** [comment] 2023-01-07 00:51
yeah,me too.I can’t open any versions by sink

**Comment by khanhduytran0** [comment] 2023-01-20 14:47
Duplicate of #469

**Closed by khanhduytran0** 2023-01-20 14:47 UTC
Labels: bug

**Comment by oofeternal** [comment] 2023-05-15 17:22
Same thing happens when I try to use Zink I really was looking forward to using shaders but I guess it doesn’t work in iOS 16 and later please fix this bug

**Comment by SueYanr** [comment] 2023-06-21 10:36
So , when will fix the bug?
