### ISSUE TITLE
World won’t load after saving when I close app

### ISSUE THREAD

**Issue by AdanGonz244** [PojavLauncherTeam/PojavLauncher_iOS#520] opened 2023-03-06 22:23 UTC
### Describe the bug

Whenever I make a world then decide to leave when I come back to the world it would take forever to load and still be at 0% then crash I don’t have the report of crash since this happened yesterday but if I do get a chance to get a crash report from it happening I will

### Steps To Reproduce

```markdown
1. Make a world 

2. Save and quit the world 

3. Quit Game (Main Menu Of Minecraft)

4. Quit PojavLauncher 

5. Reopen PojavLauncher 

6. Enter the version last played on

7. Try to re-enter world 

8. Wait to see if it’ll crash
```

### Expected Behavior

I expected to re enter the world and be able to play again without having to make a whole new one every time

### Platform

```markdown
- Device model: IPhone SE
- iOS version: 16.3.1
- PojavLauncher version: 2.1.3
```

**Comment by khanhduytran0** [comment] 2023-03-06 23:16
Send latestlog.txt

**Comment by crystall1nedev** [comment] 2023-04-20 14:19
Can't reproduce this issue on the latest development builds, closing.

**Closed by crystall1nedev** 2023-04-20 14:19 UTC
Labels: bug
