### ISSUE TITLE
[Bug] unable to login after migrate to Microsoft account

### ISSUE THREAD

**Issue by teelekkung** [PojavLauncherTeam/PojavLauncher_iOS#277] opened 2021-09-21 05:33 UTC
### Describe the bug

I recently migrate to Microsoft account a week ago and I just wanna play on my phone so I go delete old account (Mojave) and click Microsoft login but after I enter email and passwords the app crash .I also try dev version , it get me an error popup but the app doesn't crash

### The log file and images/videos

Error in app 

java.lang.RuntimeException: MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:177)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.run(MicrosoftAuthTask.java:39)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:38)

log file

2021-09-21 12:26:19.918 PojavLauncher[5163:63726] [Pre-Init] iPhone8,4 with iOS 14.3 (Taurine)
2021-09-21 12:26:19.918 PojavLauncher[5163:63726] [Pre-Init] PojavLauncher version: debug - 64f4042
2021-09-21 12:26:19.918 PojavLauncher[5163:63726] [Pre-init] Beginning JVM launch
2021-09-21 12:26:19.918 PojavLauncher[5163:63726] [Pre-Init] Restored preference: JAVA_HOME is set to /usr/lib/jvm/java-16-openjdk
2021-09-21 12:26:19.918 PojavLauncher[5163:63726] [Pre-Init] Restored preference: RENDERER is set to libgl4es_114.dylib
2021-09-21 12:26:19.937 PojavLauncher[5163:63726] [Pre-init] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-09-21 12:26:19.937 PojavLauncher[5163:63726] [Pre-init] Restored preference: MULTI_DIR is set to default
2021-09-21 12:26:19.937 PojavLauncher[5163:63726] [Pre-init] Java executable path: /usr/lib/jvm/java-16-openjdk/bin/java
2021-09-21 12:26:19.937 PojavLauncher[5163:63726] [Init] Found JLI lib
2021-09-21 12:26:19.937 PojavLauncher[5163:63726] [Init] Calling JLI_Launch
2021-09-21 12:26:19.938 PojavLauncher[5163:63730] [Pre-init] Reading custom environment variables (custom_env.txt), opened=0
2021-09-21 12:26:19.943 PojavLauncher[5163:63730] [Pre-Init] iPhone8,4 with iOS 14.3
2021-09-21 12:26:19.944 PojavLauncher[5163:63730] [Pre-Init] PojavLauncher version: debug - 64f4042
2021-09-21 12:26:19.944 PojavLauncher[5163:63730] [Pre-init] Beginning JVM launch
2021-09-21 12:26:19.944 PojavLauncher[5163:63730] [Pre-Init] Restored preference: JAVA_HOME is set to /usr/lib/jvm/java-16-openjdk
2021-09-21 12:26:19.944 PojavLauncher[5163:63730] [Pre-Init] Restored preference: RENDERER is set to libgl4es_114.dylib
2021-09-21 12:26:19.965 PojavLauncher[5163:63730] [Pre-init] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-09-21 12:26:19.966 PojavLauncher[5163:63730] [Pre-init] Restored preference: MULTI_DIR is set to default
2021-09-21 12:26:19.966 PojavLauncher[5163:63730] [Pre-init] RENDERER has been set to libgl4es_114.dylib
2021-09-21 12:26:19.966 PojavLauncher[5163:63730] [Init] Found JLI lib
2021-09-21 12:26:19.966 PojavLauncher[5163:63730] [Init] Calling JLI_Launch
[0.005s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016dcf8000-0x000000016dd04000).
[0.005s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-09-21 12:26:20.225 PojavLauncher[5163:63726] [Init] PojavCore loaded from vm=0x104165e50
java.lang.RuntimeException: MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:177)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.run(MicrosoftAuthTask.java:39)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:38)

2021-09-21 12:26:34.851 PojavLauncher[5163:63726] Returning local object of class NSString

### Steps To Reproduce

```markdown
In Release Version
1. Start PojavLauncher
2. Click Microsoft Login
3. Enter Email And Passwords
4. Boom App Crash 
In Dev Version
1. Start PojavLauncher
2. Click Sign In
3. Click Microsoft account
4. Enter Email And Passwords
5. Boom Error popup came
```

### Expected Behavior

I expec the app to log me in

### Platform

```markdown
- Device model: iPhone SE 2016 ( iPhone8,4 n69ap )
- iOS version: 14.3 ( odysseyra1n and taurine )
- PojavLauncher version: 1.2 and 1.3~alpha111
```

**Comment by khanhduytran0** [comment] 2021-09-21 07:36
Duplicate of #261

**Comment by khanhduytran0** [comment] 2021-09-21 07:37
See #184 for more info.

**Closed by khanhduytran0** 2021-09-21 07:36 UTC
Labels: bug
