### ISSUE TITLE
[Bug] PojavLauncher orientation is incorrect when AirPlaying

### ISSUE THREAD

**Issue by Coolpants515** [PojavLauncherTeam/PojavLauncher_iOS#431] opened 2022-11-17 19:53 UTC
### Describe the bug

When I airplay Minecraft to the my TV it goes in like a weird mode and Yes the picture was taken when I was on modded version but I changed to the normal version after and still like this

### The log file and images/videos

![2D13A2CD-C05B-4DA3-ACF5-EFA595EF77B2](https://user-images.githubusercontent.com/118224613/202544933-7b7236c6-acbb-4e94-8e8f-0b93fee2c7f1.jpeg)

### Steps To Reproduce

```markdown
1. Airplay to a supported tv
2. Go to PojavLauncher
3. Press Play
```

### Expected Behavior

I expect it to look the same way that is on my phone when I am not airplay it landscape mode not this

### Platform

```markdown
- Device model: IPhone 12
- iOS version: 16
- PojavLauncher version: 2.0.1
```

### Anything else?

I’m not on a jailbreak phone just so you know

**Comment by khanhduytran0** [comment] 2022-11-17 23:56
2.0.1 is outdated, however it was not the version that supported fullscreen AirPlaying.
Please send log.

**Comment by Coolpants515** [comment] 2022-11-18 19:21
It version 2.1 actually I messed up sorry and where do I find that?

**Comment by khanhduytran0** [comment] 2022-11-19 04:29
Not sure if it's related, but please try [this build](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/3501987087)

**Comment by Coolpants515** [comment] 2022-11-20 18:49
Do I just install the ipa normally?

**Comment by crystall1nedev** [comment] 2022-12-05 17:26
This issue was reproducible, but now it has since been fixed. Closing.

**Closed by crystall1nedev** 2022-12-05 17:26 UTC
Labels: bug
