### ISSUE TITLE
[Question] <Short description>

### ISSUE THREAD

**Issue by PhanAnhT** [PojavLauncherTeam/PojavLauncher_iOS#713] opened 2024-07-03 05:42 UTC
### Ask the question here.

How to play pojav without a premium account

**Comment by Kiokingz** [comment] 2024-07-03 05:47
you can, but you need a premium account to obtain installations. we don't endorse piracy here

**Comment by Kiokingz** [comment] 2024-07-03 05:56
also, don't create an issue over and over again, this is a duplicate of #712

**Closed** 2024-07-03 08:45 UTC
Labels: question
