### ISSUE TITLE
[Bug] Cannot Launch Minecraft after Choosing "Zink" Renderer

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [PojavLauncherTeam/PojavLauncher_iOS#373] opened 2022-08-25 06:52 UTC
### Describe the bug

After choosing "Zink" renderer and start MC in PojavLauncher, nothing will be displayed, except "controls"

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/9422019/latestlog.txt)
![IMG_3750](https://user-images.githubusercontent.com/42903464/186592132-4d9bbec5-0a71-434d-97c6-0694bbc40111.PNG)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Choose "Zink" Renderer
3. Launch MC
```

### Expected Behavior

Started the game normally.

### Platform

```markdown
- Device model: iPhone 12
- iOS version: 15.6/ 16.0 Developer Beta 6
- PojavLauncher version: Latest Release
```

### Anything else?

I tested MC 1.16.5-1.19, but the results were the same.

**Comment by Aerolome** [comment] 2022-08-25 07:04
it works, its just not displaying anything, try pressing F2 for screenshot

**Comment by Shiroiame-Kusu** [comment] 2022-08-25 07:18
I saw the screenshots, MC seems to be OK.
But the screen is still in black, how can i play Minecraft (With Zink) normally?

**Comment by Shiroiame-Kusu** [comment] 2022-08-25 07:19
> it works, its just not displaying anything, try pressing F2 for screenshot

I saw the screenshots, MC seems to be OK.
But the screen is still in black, how can i play Minecraft (With Zink) normally?

**Comment by Aerolome** [comment] 2022-08-25 07:42
> > it works, its just not displaying anything, try pressing F2 for screenshot
> 
> I saw the screenshots, MC seems to be OK. But the screen is still in black, how can i play Minecraft (With Zink) normally?

no, but the devs are working on zink currently quite a bit

**Comment by BigBoiMan123** [comment] 2022-10-15 03:26
Still like this 2 months later...

**Comment by Shiroiame-Kusu** [comment] 2022-10-20 11:48
> Still like this 2 months later...

I really hope that developers will solve this problem

**Comment by Shiroiame-Kusu** [comment] 2022-10-20 12:08
> I’m not sure what went wrong, but you were using the one from `main` branch, which should render with not-so-good performance.

So what should I do next in order to offer more information about this “bug”

**Comment by khanhduytran0** [comment] 2022-10-20 12:23
Try with the latest build I guess.
Additionally, there is [a more recent build of Mesa Zink](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions?query=branch%3Azink-update) but packaged in an older launcher commit, as an effort to hope for the performance.

> or

*You can’t play with just one of those solved*. The only purpose that I can think of for using Zink is shader, which will drop performance even more.
Apparently I’m not a Zink dev so I couldn’t figure out what’s slowing down Zink. I ~~kinda lost interest in it~~ am still waiting for news from its developers.

**Comment by Shiroiame-Kusu** [comment] 2022-10-20 12:44
> Try with the latest build I guess. Additionally, there is [a more recent build of Mesa Zink](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions?query=branch%3Azink-update) but packaged in an older launcher commit, as an effort to hope for the performance.
> 
> > or
> 
> _You can’t play with just one of those solved_. The only purpose that I can think of for using Zink is shader, which will drop performance even more. Apparently I’m not a Zink dev so I couldn’t figure out what’s slowing down Zink. I ~kinda lost interest in it~ am still waiting for news from its developers.

Thanks for your reply，I‘ll try that build this weekend.
In fact，the purpose of using Zink is trying to get better performance while playing Minecraft Java Edition on my iPhone. Because tiny4angle didn‘t support Sodium mod at all. So the performance is really bad.
（30-50fps，75%scaled，mc1.19）
Although you said that you’re kinda lost interested in Zink，I still believe that you will bring a better PojavLauncher-iOS to us.
I’ll leave this issue open，looking forward to hearing from your good news.
Best Wishes.

**Comment by crystall1nedev** [comment] 2022-10-20 12:53
You might be keeping this issue open, but I’m closing it as it is resolved. The Zink renderer was intended to serve as a replacement for GL4ES after 1.17 released - but the lack of knowledge, performance, and rise of other renderers killed off the need to work with it.

Yes, some things don’t work in GL4ES. But once the data is actually produced, you can see that Zink isn’t much better in that regard. It *works*, but it’s not going to be a fun experience. For example, Zink and Sodium 1.19.2 perform at 20-30FPS on my iPhone X, which is actuall

**Closed by crystall1nedev** 2022-10-20 12:53 UTC
Labels: bug

**Comment by khanhduytran0** [comment] 2022-10-20 12:55
[VulkanMod](https://github.com/PojavLauncherTeam/VulkanMod/actions) might be what you're looking for.
It's pretty cool that it doubles the performance compared to ANGLE (this was tested by an A13 user).

**Comment by Shiroiame-Kusu** [comment] 2022-10-20 13:01
> [VulkanMod](https://github.com/PojavLauncherTeam/VulkanMod/actions) might be what you're looking for.
> It's pretty cool that it doubles the performance compared to ANGLE (this was tested by an A13 user).

Sorry to say that.
I‘ve tested it on my iPhone12，but the performance getting worse after adding it.

**Comment by Shiroiame-Kusu** [comment] 2022-10-20 13:13
> [VulkanMod](https://github.com/PojavLauncherTeam/VulkanMod/actions) might be what you're looking for. It's pretty cool that it doubles the performance compared to ANGLE (this was tested by an A13 user).
> 
> Quick comparison from the tester:
> 
> 1.18.2 vanilla, ANGLE ![1](https://camo.githubusercontent.com/c07ade515cb517e720a6382cd73df691e9ca57eeacbea6b87a91ceb6c8730a3a/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3939343431313135303236313336323638382f313032363436333131333537323237303135302f494d475f373333302e706e67)
> 
> 1.19 Vulkan ![2](https://camo.githubusercontent.com/9c30de68ade7c6127adeb0669ad08f0fa49d892344a0db88b54024fa8ebd080d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3939343431313135303236313336323638382f313032363436333131333931363139303734302f494d475f373333362e706e67)

> [VulkanMod](https://github.com/PojavLauncherTeam/VulkanMod/actions) might be what you're looking for. It's pretty cool that it doubles the performance compared to ANGLE (this was tested by an A13 user).
> 
> Quick comparison from the tester:
> 
> 1.18.2 vanilla, ANGLE ![1](https://camo.githubusercontent.com/c07ade515cb517e720a6382cd73df691e9ca57eeacbea6b87a91ceb6c8730a3a/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3939343431313135303236313336323638382f313032363436333131333537323237303135302f494d475f373333302e706e67)
> 
> 1.19 Vulkan ![2](https://camo.githubusercontent.com/9c30de68ade7c6127adeb0669ad08f0fa49d892344a0db88b54024fa8ebd080d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3939343431313135303236313336323638382f313032363436333131333931363139303734302f494d475f373333362e706e67)

Here are my results.（I even added a fan behind my phone）
tiny4angle  
![3EA66102-81E7-4727-BB2F-A6D48A5B7C15](https://user-images.githubusercontent.com/42903464/196958101-65a307d8-6151-4039-8d85-6836445d6f3b.png)
Vulkan Mod  
![4BF670D1-1E86-479C-9B78-4F9CB7846A03](https://user-images.githubusercontent.com/42903464/196958228-e1ea6378-9d16-4b9a-b5bd-6e26089d5fda.png)

**Comment by khanhduytran0** [comment] 2022-10-20 13:22
Do you have any other mods installed?
Seems like Fabric API is there, so I guess there’s a lot.
