### ISSUE TITLE
Black screen issue with Zink renderer ipados 16 

### ISSUE THREAD

**Issue by abhishekgi** [PojavLauncherTeam/PojavLauncher_iOS#491] opened 2023-01-19 17:22 UTC
### Describe the bug

When I launch game with Zink renderer the screen remain black for all time however I noticed sound of game come and when I randomly tap on button the button tapping sound also come but screen remain totaly black my ios version is ipados 16.2. many people had already reported this bug I am unable to understand why pojav launcher team is not fixing it 

### Steps To Reproduce

```markdown
Start pojav launcher on ipados 16.2
Select Zink renderer and lunch the game the screen will remain black however the sound of game come and when I randomly tap on button the button tapping sound also come but screen remain totaly black.
```

### Expected Behavior

I want to play with shaders using Zink renderer but how can I if screen remain black on ipados 16 😭😭😭

### Platform

```markdown
- Device model:iPad 9
- iOS version: ipados 16.2
- PojavLauncher version: V2.1.2
```

### Anything else?

Please fix bug I want to play with shaders using Zink renderer 😭😭😭😭😭

**Comment by khanhduytran0** [comment] 2023-01-20 14:48
Duplicate of #469

**Closed by khanhduytran0** 2023-01-20 14:48 UTC
Labels: bug

**Comment by l9njiezxc** [comment] 2023-01-22 10:20
Enable JIT

**Comment by abhishekgi** [comment] 2023-01-26 12:00
> Enable JIT

What are you fool
